sudo: required  
language: node_js
node_js:
- "4.3.2"
services:
- elasticsearch
before_install:
# decrypt configs
- openssl aes-256-cbc -K $encrypted_6fe224c112de_key -iv $encrypted_6fe224c112de_iv -in travis.enc -out travis.zip -d
- unzip travis.zip
# apt dependencies
- sudo apt-get -qq update
- sudo apt-get install wget python-setuptools lsof unzip inkscape imagemagick ruby ruby-dev libnss3 libnss3-dev xvfb libnss3-1d libexif-dev curl build-essential libssl-dev libappindicator1 fonts-liberation -y
# api
- export RAILS_ENV=development
- git clone https://github.com/meedan/check-api.git
- cp travis/check-api.yml check-api/config/config.yml
- cp check-api/config/initializers/secret_token.rb.example check-api/config/initializers/secret_token.rb
- cp check-api/config/database.yml.travis check-api/config/database.yml
- cd check-api
- bundle install
- bundle exec rake db:migrate
- rails s -p 3000 &
- cd -
# pender
- git clone https://github.com/meedan/pender.git
- cp travis/pender.yml pender/config/config.yml
- cp pender/config/initializers/secret_token.rb.example pender/config/initializers/secret_token.rb
- cp pender/config/database.yml.travis pender/config/database.yml
- cd pender
- bundle install
- bundle exec rake db:migrate
- rails runner 'a = ApiKey.create!; a.access_token = "test"; a.save!'
- rails s -p 3005 &
- cd -
# xvfb
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
# google chrome
- export CHROME_BIN=/usr/bin/google-chrome
- sudo apt-get -qq update
- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
- sudo dpkg -i google-chrome*.deb
- google-chrome --no-sandbox &
# chromedriver
- wget http://chromedriver.storage.googleapis.com/2.20/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- sudo mv chromedriver /usr/local/bin
- sudo chmod a+x /usr/local/bin/chromedriver
- chromedriver &
# ruby / bundler / rspec
- gem install bundler
- cd test && bundle install && cd -
# config files
- cp travis/config.js config.js
- cp travis/config.yml test/config.yml
before_script:
- sleep 5
- npm install
- npm run build
- export SERVER_PORT=3333
- npm run publish &
- sleep 5
script: npm run test
# add Slack here
