sudo: required  
dist: trusty
language: node_js
node_js:
- "4.3.2"
services:
- elasticsearch
before_install:
# apt dependencies
- sudo apt-get -qq update
- sudo apt-get install wget python-setuptools lsof unzip inkscape imagemagick ruby ruby-dev libnss3 libnss3-dev xvfb libnss3-1d libexif-dev curl build-essential libssl-dev libappindicator1 fonts-liberation -y
# api
- git clone https://github.com/meedan/check-api.git
- openssl aes-256-cbc -K $encrypted_2e9696b0f841_key -iv $encrypted_2e9696b0f841_iv -in travis/check-api.enc -out bridge-api/config/config.yml -d
- cd check-api && bundle install
- cp bridge-api/config/initializers/secret_token.rb.example bridge-api/config/initializers/secret_token.rb
- cp bridge-api/config/database.yml.travis bridge-api/config/database.yml
- RAILS_ENV=development bundle exec rake db:migrate
- rails s -p 3000 &
# pender
- git clone https://github.com/meedan/pender.git
- openssl aes-256-cbc -K $encrypted_6fe224c112de_key -iv $encrypted_6fe224c112de_iv -in travis/pender.enc -out pender/config/config.yml -d
- cd pender && bundle install
- cp pender/config/initializers/secret_token.rb.example pender/config/initializers/secret_token.rb
- cp pender/config/database.yml.travis pender/config/database.yml
- RAILS_ENV=development bundle exec rake db:migrate
- rails runner 'a = ApiKey.create!; a.access_token = "test"; a.save!'
- rails s -p 3005 &
# xvfb
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
# google chrome
- export CHROME_BIN=/usr/bin/google-chrome
- sudo apt-get -qq update
- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
- sudo dpkg -i google-chrome*.deb
- google-chrome --no-sandbox &
# chromedriver
- wget http://chromedriver.storage.googleapis.com/2.20/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- sudo mv chromedriver /usr/local/bin
- sudo chmod a+x /usr/local/bin/chromedriver
- chromedriver &
# ruby / bundler / rspec
- gem install bundler
- cd test && bundle install && cd -
# config files
- openssl aes-256-cbc -K $encrypted_6fe224c112de_key -iv $encrypted_6fe224c112de_iv -in travis/config.js.enc -out config.js -d
- openssl aes-256-cbc -K $encrypted_2e9696b0f841_key -iv $encrypted_2e9696b0f841_iv -in travis/config.yml.enc -out test/config.yml -d
before_script:
- sleep 5
- npm install
- npm run build
- export SERVER_PORT=3333
- npm run publish &
- sleep 5
script: npm run test
# add Slack here
