sudo: required
dist: trusty
language: node_js
services:
- postgresql
node_js:
- "6.9.2"
addons:
  postgresql: "9.4"
before_install:
# decrypt configs
- openssl aes-256-cbc -K $encrypted_5ab85c42c496_key -iv $encrypted_5ab85c42c496_iv -in travis.enc -out travis.zip -d
- unzip travis.zip
# apt dependencies
- sudo apt-get -qq update
- sudo apt-get install wget python-setuptools lsof unzip inkscape imagemagick ruby ruby-dev libnss3 libnss3-dev xvfb libnss3-1d libexif-dev curl build-essential libssl-dev libappindicator1 fonts-liberation redis-server -y
# check api
- psql -c 'create database checkapi;' -U postgres
- redis-server &
- curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.2.4.deb && sudo dpkg -i --force-confnew elasticsearch-1.2.4.deb && sudo service elasticsearch restart
- git clone https://github.com/meedan/check-api.git
- cp travis/check-api.yml check-api/config/config.yml
- cp check-api/config/initializers/secret_token.rb.example check-api/config/initializers/secret_token.rb
- cp travis/check-api-database.yml check-api/config/database.yml
- cd check-api
- bundle install
- bundle exec rake db:migrate RAILS_ENV=test
- rails s -e test -p 3000 >/dev/null &
- cd -
- export RAILS_ENV=development
# pender
- git clone https://github.com/meedan/pender.git
- cp travis/pender.yml pender/config/config.yml
- cp pender/config/initializers/secret_token.rb.example pender/config/initializers/secret_token.rb
- cp pender/config/database.yml.travis pender/config/database.yml
- cd pender
- bundle install
- bundle exec rake db:migrate
- rails runner 'a = ApiKey.create!; a.access_token = "test"; a.save!'
- rails s -p 3005 >/dev/null &
- cd -
# xvfb
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
# google chrome
- sudo apt-get -qq update
- sudo apt-get install chromium-browser -y
- export CHROME_BIN=/usr/bin/chromium-browser
- chromium-browser --no-sandbox &
# chromedriver
- wget http://chromedriver.storage.googleapis.com/2.28/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- sudo mv chromedriver /usr/local/bin
- sudo chmod a+x /usr/local/bin/chromedriver
- chromedriver >/dev/null 2>/dev/null &
# ruby / bundler / rspec
- gem install bundler
- cd test && bundle install && cd -
# config files
- cp travis/config.js config.js
- cp travis/config.js test/config.js
- cp travis/config.yml test/config.yml
before_script:
- sleep 5
- npm install
- npm run build
- export SERVER_PORT=3333
- npm run publish &
- sleep 5
after_script:
- size=$(du -k build/web/js/index.bundle.js | cut -f1) && size2=$(du -k build/web/js/vendor.bundle.js | cut -f1) && totalsize=$((size+size2)) && echo "Your bundle size is $totalsize kb"
script: npm run test
notifications:
  slack:
    secure: "f/6GBO4+yZgpHnTOsCUpfhQs4z64tgmvyXDhLisSa032a+Bh1xvYNQpx0GUREdkoWv+R3YDIRmdCEd+FXPDNfjBzBwnF8NieLQX7RHUztharbZIhxZhLwBHPr3xlJildJzOairN190t8WM+fLQRSw2vybE+UwQmy8Bj+263azSutDYAyEyYUQ6r/43b6ov49j3zQW2S3kL/OM8s/sYYwGn46PJe9tndWseokW3jV0UNHWmi70zcDN11rnCYTXwmAlqKQrPJ0M37aVLFIVYw4ZQFVVnzfUIeqjsDL0x1NpQOqk7QTvhmH50QP5DZ+JpKqXV1TB4/9tThmDUKeiGAiXdfn1FiLeNd7K8UyczhEOHbGa8A1H7W7LHNqPp/CuPbdDf08KLfRIioFKLW4N9qMARcZHJ5FymRbL+RW+37+bcAEAK/uojEp+sH9CNbm93zg85vvVc20CsqUy2ud50RUkKHqNbQWKihN/1wPIBgapjY/LJ8LuHppACocUHjgm0hKedaC20uVcdEG65nttwxq4Sp5H/BrBPUZxBZ8I54Xxv/BM4b0wRyPFb38jeGXM63OL2w88/c6+FQFkjSGZYOgf3M7UySydpDdvJRr67EADW8QE6Hv90xviEn98MAHZ0hQarzfl1bFfX1OF2D6TqXPvtwtB0NNJ1WlayD1BTNb0pw="
