sudo: required
dist: trusty
language: node_js
services:
- docker
- postgresql
node_js:
- "6.9.2"
rvm:
- 2.3.1
addons:
  postgresql: "9.4"

before_install:
# decrypt configs
- openssl aes-256-cbc -K $encrypted_bae357cf8888_key -iv $encrypted_bae357cf8888_iv -in travis.zip.enc -out travis.zip -d
- unzip travis.zip

# create database
- psql -c 'create database checkapi;' -U postgres



# check api
- cp travis/check-api.yml ./.travis/check-api/config.yml
- cp travis/check-api-database.yml ./.travis/check-api/database.yml

# pender
- cp travis/pender.yml ./.travis/pender/config.yml

# bring up docker containers so they have time to come up
- cd .travis && docker-compose up -d && cd -

# additional docker container config
- cd .travis
- docker-compose exec check-api mkdir -p /app/shared/config/initializers
- docker-compose exec check-api cp /app/current/config/initializers/secret_token.rb.example /app/shared/config/initializers/secret_token.rb
- docker-compose exec pender cp /app/pender/current/config/database.yml.travis /app/pender/shared/config/database.yml
- docker-compose exec pender cp /app/pender/current/config/sidekiq.yml.travis /app/pender/shared/config/sidekiq.yml
- docker-compose exec check-api mkdir -p /app/pender/shared/config/initializers
- docker-compose exec pender cp /app/pender/current/config/initializers/secret_token.rb.example /app/pender/shared/config/initializers/secret_token.rb
# I think these both do the same thing
- docker-compose exec check-api bundle exec rake lapis:api_keys:create_default RAILS_ENV=test
- docker-compose exec pender rails runner 'a = ApiKey.create!; a.access_token = "test"; a.save!'
- cd -

# apt dependencies
- sudo apt-get -qq update
- sudo apt-get install wget python-setuptools lsof unzip inkscape imagemagick ruby ruby-dev libnss3 libnss3-dev xvfb libnss3-1d libexif-dev curl build-essential libssl-dev libappindicator1 fonts-liberation chromium-browser -y
- rvm install 2.3.1
- rvm --default use 2.3.1

# xvfb
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

# google chrome
- export CHROME_BIN=/usr/bin/chromium-browser
- chromium-browser --no-sandbox &

# chromedriver
- wget http://chromedriver.storage.googleapis.com/2.28/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- sudo mv chromedriver /usr/local/bin
- sudo chmod a+x /usr/local/bin/chromedriver
- chromedriver >/dev/null 2>/dev/null &

# check-web config
- cp travis/config-build.js config-build.js
- cp travis/config-server.js config-server.js
- cp travis/config.js config.js
- cp travis/config.js test/config.js
- cp travis/config.yml test/config.yml


# ruby / bundler / rspec
- gem install bundler
- cd test && bundle install && cd -


before_script:
- sleep 5
- npm install
- npm run build
- export SERVER_PORT=3333
- npm run publish &
- sleep 5
script: npm run test
after_script:
- size=$(du -k build/web/js/index.bundle.js | cut -f1) && size2=$(du -k build/web/js/vendor.bundle.js | cut -f1) && totalsize=$((size+size2)) && echo "Your bundle size is $totalsize kb"
notifications:
  slack:
    secure: TAPzV/OeN5hl8JSGrqPcAtFO/NWa9IqMbyzuUpCZgNP9EbobmlTPx55mopI647rwVIQZM1RL+2SapHJbT7XCAjJ+uvzSQd0b/LaS/aXLKFcS3bBDcvKAUeCcCYUiDz7x832EYg0fsVErR2dZPxvuPtWtwrOlOaOo8HB1uVHjvKo20Wnr/J4+VNTGvhQ5awdmpHMh+KrWpjQi4Ta9zWOTmSYh3qhgaLKjIKXanoaWen87VJB6Jy8nJ3Bo6t3r3+sbCRN9/LUZ8sVcJnvzlKdOtiLGkz8u2YG2c8UD+iUt2VOk0o5L/o8YPoeukJyFuAHAdLrjOelwHCAD2dRfrpQG7y/8G0vjJRXg8DRaVBVIl9vpYM6lyVIw5I6a9XDbUeOnBAWHE3uj/xH0X0vcRREE5py6tbt1KPUBS9rc8JGdCW3ZXVZAXA+1cijR3AAZUZ0YEf9WKLYhsTFW9lYlDcmkrWgVD9vbtPGDg95sbtuB+H5dkEAOBkf2YGkqzO+aaQKLDHkib/1v4C1+T5lXqlWZUrP8EuRwWs6xJlhi6w72AZLo7kVmfGA3ZdKfVcPCqr83YBfhL0WbwgT94L+5STELxw/PhsyNyOM/sRLQgR24ga/lcg2+L395VIPrQvhgKc26yHBuqW2P6FSOEGMyEcZ34N1TMTtRF7/lkRmXyKt4zuc=
